// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proton.Server.Infrastructure.Persistence;

#nullable disable

namespace Proton.Server.Resource.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20240105193050_Create_RaceMap_RacePoint_RaceStartPoint")]
    partial class Create_RaceMap_RacePoint_RaceStartPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proton.Shared.Models.RaceMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("RaceMap");
                });

            modelBuilder.Entity("Proton.Shared.Models.RacePoint", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Proton.Shared.Models.RacePoint.Position#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.HasKey("MapId", "Index");

                    b.ToTable("RacePoint");
                });

            modelBuilder.Entity("Proton.Shared.Models.RaceStartPoint", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Proton.Shared.Models.RaceStartPoint.Position#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.HasKey("MapId", "Index");

                    b.ToTable("RaceStartPoint");
                });

            modelBuilder.Entity("Proton.Shared.Models.RacePoint", b =>
                {
                    b.HasOne("Proton.Shared.Models.RaceMap", "Map")
                        .WithMany("RacePoints")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Proton.Shared.Models.RaceStartPoint", b =>
                {
                    b.HasOne("Proton.Shared.Models.RaceMap", "Map")
                        .WithMany("StartPoints")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Proton.Shared.Models.RaceMap", b =>
                {
                    b.Navigation("RacePoints");

                    b.Navigation("StartPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
