// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proton.Server.Infrastructure.Persistence;

#nullable disable

namespace Proton.Server.Resource.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20241021083214_OwnedTunings")]
    partial class OwnedTunings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proton.Server.Core.Models.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterGender")
                        .HasColumnType("integer");

                    b.Property<int>("EyeColor")
                        .HasColumnType("integer");

                    b.Property<int>("Eyebrows")
                        .HasColumnType("integer");

                    b.Property<int>("EyebrowsColor")
                        .HasColumnType("integer");

                    b.Property<int>("FaceFather")
                        .HasColumnType("integer");

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("FaceMix")
                        .HasColumnType("real");

                    b.Property<int>("FaceMother")
                        .HasColumnType("integer");

                    b.Property<string>("FaceOverlays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FacialHair")
                        .HasColumnType("integer");

                    b.Property<float>("FacialHairOpacity")
                        .HasColumnType("real");

                    b.Property<int>("FirstFacialHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("FirstHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("HairDrawable")
                        .HasColumnType("integer");

                    b.Property<int>("SecondFacialHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("SecondHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("SkinFather")
                        .HasColumnType("integer");

                    b.Property<float>("SkinMix")
                        .HasColumnType("real");

                    b.Property<int>("SkinMother")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Log.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipv4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipv6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimestampLogout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.OwnedVehicleTuning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnedVehicleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isEquiped")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnedVehicleId");

                    b.ToTable("OwnedVehicleTuning");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IplName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("RaceMaps");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RacePoint", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Proton.Server.Core.Models.RacePoint.Position#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.HasKey("MapId", "Index");

                    b.ToTable("RacePoints");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceStartPoint", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Proton.Server.Core.Models.RaceStartPoint.Position#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Rotation", "Proton.Server.Core.Models.RaceStartPoint.Rotation#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.HasKey("MapId", "Index");

                    b.ToTable("RaceStartPoints");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.UserRaceRestoration", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<float>("AccumulatedDistance")
                        .HasColumnType("real");

                    b.Property<long>("FinishTime")
                        .HasColumnType("bigint");

                    b.Property<int>("Lap")
                        .HasColumnType("integer");

                    b.Property<int?>("NextRacePointIndex")
                        .HasColumnType("integer");

                    b.Property<float>("PartialDistance")
                        .HasColumnType("real");

                    b.Property<float>("Pitch")
                        .HasColumnType("real");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<float>("Roll")
                        .HasColumnType("real");

                    b.Property<long>("VehicleModel")
                        .HasColumnType("bigint");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<float>("Yaw")
                        .HasColumnType("real");

                    b.Property<float>("Z")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.ToTable("UserRaceRestorations");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltVHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Proton.Server.Core.Models.VehicleTuning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleTunings");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.OwnedVehicle", b =>
                {
                    b.HasBaseType("Proton.Server.Core.Models.Vehicle");

                    b.Property<string>("AltVColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorDisplayname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("OwnedVehicle");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Character", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "User")
                        .WithOne("Character")
                        .HasForeignKey("Proton.Server.Core.Models.Character", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Log.Session", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "_User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_User");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.OwnedVehicleTuning", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.OwnedVehicle", null)
                        .WithMany("Tunings")
                        .HasForeignKey("OwnedVehicleId");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RacePoint", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.RaceMap", "Map")
                        .WithMany("RacePoints")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceStartPoint", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.RaceMap", "Map")
                        .WithMany("StartPoints")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.UserRaceRestoration", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Proton.Server.Core.Models.UserRaceRestoration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Proton.Server.Core.Models.UserRacePointRestoration", "Points", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Index")
                                .HasColumnType("integer");

                            b1.Property<int>("Lap")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("Time")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserId", "Index");

                            b1.ToTable("UserRacePointRestoration");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Points");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.OwnedVehicle", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", null)
                        .WithMany("OwnedVehicles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceMap", b =>
                {
                    b.Navigation("RacePoints");

                    b.Navigation("StartPoints");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.User", b =>
                {
                    b.Navigation("Character");

                    b.Navigation("OwnedVehicles");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.OwnedVehicle", b =>
                {
                    b.Navigation("Tunings");
                });
#pragma warning restore 612, 618
        }
    }
}
