// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proton.Server.Infrastructure.Persistence;

#nullable disable

namespace Proton.Server.Resource.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20250111125211_PlayerVehicleActiveMod")]
    partial class PlayerVehicleActiveMod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proton.Server.Core.Models.BanRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("BanRecords");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterGender")
                        .HasColumnType("integer");

                    b.Property<int>("EyeColor")
                        .HasColumnType("integer");

                    b.Property<int>("Eyebrows")
                        .HasColumnType("integer");

                    b.Property<int>("EyebrowsColor")
                        .HasColumnType("integer");

                    b.Property<int>("FaceFather")
                        .HasColumnType("integer");

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("FaceMix")
                        .HasColumnType("real");

                    b.Property<int>("FaceMother")
                        .HasColumnType("integer");

                    b.Property<string>("FaceOverlays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FacialHair")
                        .HasColumnType("integer");

                    b.Property<float>("FacialHairOpacity")
                        .HasColumnType("real");

                    b.Property<int>("FirstFacialHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("FirstHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("HairDrawable")
                        .HasColumnType("integer");

                    b.Property<int>("SecondFacialHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("SecondHairColor")
                        .HasColumnType("integer");

                    b.Property<int>("SkinFather")
                        .HasColumnType("integer");

                    b.Property<float>("SkinMix")
                        .HasColumnType("real");

                    b.Property<int>("SkinMother")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Log.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipv4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipv6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimestampLogout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Mod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<uint?>("Model")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Model");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.PlayerVehicleActiveMod", b =>
                {
                    b.Property<long>("PlayerVehicleModId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerVehicleModId");

                    b.ToTable("PlayerVehicleActiveMods");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.PlayerVehicleMod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ModId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerVehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.HasIndex("PlayerVehicleId", "ModId")
                        .IsUnique();

                    b.ToTable("PlayerVehicleMods");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IplName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("RaceMaps");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RacePoint", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Proton.Server.Core.Models.RacePoint.Position#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.HasKey("MapId", "Index");

                    b.ToTable("RacePoints");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceStartPoint", b =>
                {
                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Proton.Server.Core.Models.RaceStartPoint.Position#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Rotation", "Proton.Server.Core.Models.RaceStartPoint.Rotation#Vector3", b1 =>
                        {
                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");
                        });

                    b.HasKey("MapId", "Index");

                    b.ToTable("RaceStartPoints");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.Closet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClothId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEquiped")
                        .HasColumnType("boolean");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PurchaseTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClothId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Closets");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.Cloth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Component")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DlcName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Drawable")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDlc")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProp")
                        .HasColumnType("boolean");

                    b.Property<int>("Palette")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Texture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cloths");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.PlayerVehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AltVColor")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Model")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("PrimaryColor", "Proton.Server.Core.Models.Shop.PlayerVehicle.PrimaryColor#Rgba", b1 =>
                        {
                            b1.Property<byte>("A")
                                .HasColumnType("smallint");

                            b1.Property<byte>("B")
                                .HasColumnType("smallint");

                            b1.Property<byte>("G")
                                .HasColumnType("smallint");

                            b1.Property<byte>("R")
                                .HasColumnType("smallint");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SecondaryColor", "Proton.Server.Core.Models.Shop.PlayerVehicle.SecondaryColor#Rgba", b1 =>
                        {
                            b1.Property<byte>("A")
                                .HasColumnType("smallint");

                            b1.Property<byte>("B")
                                .HasColumnType("smallint");

                            b1.Property<byte>("G")
                                .HasColumnType("smallint");

                            b1.Property<byte>("R")
                                .HasColumnType("smallint");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerVehicles");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.StockVehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StockVehicles");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.UserRaceRestoration", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<float>("AccumulatedDistance")
                        .HasColumnType("real");

                    b.Property<long>("FinishTime")
                        .HasColumnType("bigint");

                    b.Property<int>("Lap")
                        .HasColumnType("integer");

                    b.Property<int?>("NextRacePointIndex")
                        .HasColumnType("integer");

                    b.Property<float>("PartialDistance")
                        .HasColumnType("real");

                    b.Property<float>("Pitch")
                        .HasColumnType("real");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<float>("Roll")
                        .HasColumnType("real");

                    b.Property<long>("VehicleModel")
                        .HasColumnType("bigint");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<float>("Yaw")
                        .HasColumnType("real");

                    b.Property<float>("Z")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.ToTable("UserRaceRestorations");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Character", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "User")
                        .WithOne("Character")
                        .HasForeignKey("Proton.Server.Core.Models.Character", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Log.Session", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "_User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_User");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.PlayerVehicleActiveMod", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.PlayerVehicleMod", "PlayerVehicleMod")
                        .WithOne()
                        .HasForeignKey("Proton.Server.Core.Models.PlayerVehicleActiveMod", "PlayerVehicleModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerVehicleMod");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.PlayerVehicleMod", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proton.Server.Core.Models.Shop.PlayerVehicle", "PlayerVehicle")
                        .WithMany()
                        .HasForeignKey("PlayerVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");

                    b.Navigation("PlayerVehicle");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RacePoint", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.RaceMap", "Map")
                        .WithMany("RacePoints")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceStartPoint", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.RaceMap", "Map")
                        .WithMany("StartPoints")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.Closet", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.Shop.Cloth", "ClothItem")
                        .WithMany("Closets")
                        .HasForeignKey("ClothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proton.Server.Core.Models.User", "Owner")
                        .WithMany("Closets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClothItem");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.PlayerVehicle", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "Player")
                        .WithMany("Vehicles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.UserRaceRestoration", b =>
                {
                    b.HasOne("Proton.Server.Core.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Proton.Server.Core.Models.UserRaceRestoration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Proton.Server.Core.Models.UserRacePointRestoration", "Points", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Index")
                                .HasColumnType("integer");

                            b1.Property<int>("Lap")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("Time")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserId", "Index");

                            b1.ToTable("UserRacePointRestoration");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Points");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.RaceMap", b =>
                {
                    b.Navigation("RacePoints");

                    b.Navigation("StartPoints");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.Shop.Cloth", b =>
                {
                    b.Navigation("Closets");
                });

            modelBuilder.Entity("Proton.Server.Core.Models.User", b =>
                {
                    b.Navigation("Character");

                    b.Navigation("Closets");

                    b.Navigation("Sessions");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
