name = 'Proton Sports'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['csharp-module']
resources = [
    'proton-ui',
    'proton-server',
    'proton-client',
    'sport_maps_to_load',
    'sport_stunt_prop_fix',
    'dlc_mpexample',
    'dlc_sport_scaleform_core',
]
debug = true
spawnAfterConnect = false
enableSyncedMetaData = true
resourceContainerizerMode = true

[csharp-module]
disableDependencyDownload = true
